tasks: Make container work with toolbox
Move user home directory from /user/home to /work.  This avoids having
a non-empty /home, which breaks podman/toolbox when bind-mounting the
user's real home directory into the container:

    Error: failed to redirect /home to /var/home: remove /home: directory not empty

Also drop statically defining `$HOME`, it overrides the toolbox user's
home directory otherwise. Instead, set it in cockpit-tasks.

With this change, the cockpit/tasks container can effortlessly be used
with toolbox. Document how to do that.