workflows: Build ARM tasks image on GitHub runner
Commit a4c513ac49 moved the workflow to checkout@v5. The buildjet
runners don't get along with this, apparently they don't have a new
enough nodejs installed yet:

> Error: System.ArgumentOutOfRangeException:
> Specified argument was out of the range of valid values.
> (Parameter ''using: node24' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')

Move to a GitHub ARM runner instead.